name: Telestick
version: '${project.version}'
main: xyz.maciejniziolek.telestick.Telestick
api-version: 1.19
authors: [ rxtthin ]
description: Stick that can teleport you to any player
website: maciejniziolek.xyz
commands:
  ts:
    description: "Opens the telestick menu"
    permission: "telestick"
  ts-version:
    description: "Get the current Telestick plugin version"
    permission: "telestick-version"