name: Telestick
version: '${project.version}'
main: xyz.maciejniziolek.telestick.Telestick
api-version: 1.19
authors: [ rxtthin ]
description: Teleport util
website: maciejniziolek.xyz
commands:
  ts:
    permission: "telestick"